name: Test downstream projects

on:
  push:
    branches: "master"
  pull_request:
    branches: "*"

jobs:
  downstream1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Test nbclient
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: nbclient
          env_values: IPYKERNEL_CELL_NAME=\<IPY-INPUT\>

      - name: Test jupyter_client
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: jupyter_client

  downstream2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Test ipyparallel
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: ipyparallel

      - name: Test jupyter_kernel_test
        run: |
          git clone https://github.com/jupyter/jupyter_kernel_test.git
          cd jupyter_kernel_test
          pip install -e ".[test]"
          python test_ipykernel.py
